# 消息推送表
DROP TABLE IF EXISTS `GHEALTH_MESSAGE_SEND`;
CREATE TABLE `GHEALTH_MESSAGE_SEND` (
  `ID` varchar(64) NOT NULL    COMMENT '主键',
  `TITLE` varchar(255) NOT NULL,
  `CONTENT` varchar(255) NOT NULL,
  `ADDRESS` varchar(255) DEFAULT NULL,
  `PUSH_TIME` datetime NOT NULL,
    CONSTRAINT PK_MESSAGE_SEND PRIMARY KEY (`ID`)
)
;
ALTER TABLE `GHEALTH_MESSAGE_SEND` COMMENT '消息推送表';


# 消息推送代理商关联表
DROP TABLE IF EXISTS `GHEALTH_MESSAGE_SEND_AGENCY`;
CREATE TABLE `GHEALTH_MESSAGE_SEND_AGENCY` (
  `ID` varchar(64) NOT NULL,
  `MESSAGE_SEND_ID` varchar(255) NOT NULL,
  `AGENCY_ID` varchar(255) NOT NULL,
    CONSTRAINT PK_MESSAGE_SEND_AGENCY PRIMARY KEY (`ID`)
)
;
ALTER TABLE `GHEALTH_MESSAGE_SEND_AGENCY` COMMENT '消息推送代理商关联表';

INSERT INTO `ghealth_config` VALUES ('9d7c9b1a-3e17-11e8-b467-0ed5f89f718b', '/template/工单模板.xls', '工单模板.xls', '测试', '1');
